---
- name: pull wordpress image
  command: docker pull wordpress

- name: stop wordpress container
  command: docker stop mathhacks-wordpress
  ignore_errors: yes

- name: remove wordpress container
  command: docker rm mathhacks-wordpress
  ignore_errors: yes

- name: run container
  command: >
    docker run \
      -d \
      --name=mathhacks-wordpress \
      --link mathhacks-wordpress-db:mysql \
      -v /var/www/html:/var/www/html \
      -p 8080:80 \
      wordpress

- name: copy theme from S3
  command: >
    aws s3 cp s3://{{ aws_public_bucket }} /var/www/html --force --acl public-read --recursive
  environment:
    AWS_ACCESS_KEY_ID: "{{ aws_public_access_key_id }}"
    AWS_SECRET_ACCESS_KEY: "{{ aws_public_secret_access_key }}"
