---
- name: apt update
  apt:
    update_cache: yes

- name: install node
  apt:
    name: node
    state: present

- name: synchronize source folder
  synchronize:
    src: "{{ role_path }}/../../"
    dest: ~/frontend

- name: install node modules
  command: npm install

- name: build production javascript/html/css bundles
  command: npm run build:production

- name: sync backup to s3
  command: aws s3 cp ~/mysql_backup_{{ backup_timestamp }}.sql.tgz s3://{{ aws_public_bucket }} --force --acl public-read
  environment:
    AWS_ACCESS_KEY_ID: "{{ aws_public_access_key_id }}"
    AWS_SECRET_ACCESS_KEY: "{{ aws_public_secret_access_key }}"
