/* @flow */
export const POSTS = 'posts';
export const PAGES = 'pages';

export const POST_ACTION_TYPES = {
  FETCH_POST: `${POSTS}/FETCH_POST`,
  RECEIVE_POST: `${POSTS}/RECEIVE_POST`,
  FETCH_POSTS: `${POSTS}/FETCH_POSTS`,
  RECEIVE_POSTS: `${POSTS}/RECEIVE_POSTS`,

  FETCH_FEATURED_POSTS: `${POSTS}/FETCH_FEATURED_POSTS`,
  RECEIVE_FEATURED_POSTS: `${POSTS}/RECEIVE_FEATURED_POSTS`
};

export const PAGE_ACTION_TYPES = {
  FETCH_PAGES: `${PAGES}/FETCH_PAGES`,
  RECEIVE_PAGES: `${PAGES}/RECEIVE_PAGES`
};
