---
- name: create timestamp (part 1)
  command: date +"%Y%m%d"
  register: date_output

- name: create timestamp (part 2)
  set_fact:
    backup_timestamp: "{{ date_output.stdout }}"

- name: clear backup file (if it exists)
  file:
    path: ~/mysql_backup_{{ backup_timestamp }}.sql
    state: absent

- name: run mysqldump in running container
  command: >
    bash -cl "\
      docker exec mathhacks-wordpress-db \
        bash -c 'exec mysqldump --all-databases -uroot -p"{{ mysql_root_password }}"' \
        > ~/mysql_backup_{{ backup_timestamp }}.sql"

# TODO use aws cli to create backup in s3

- name: clear backup file
  file:
    path: ~/mysql_backup_{{ backup_timestamp }}.sql
    state: absent
